const products=[
{name:"Zebra Blinds",category:"Indoor",filters:["indoor","fabric"],material:"Fabric",image:"https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=85",desc:"Modern day-and-night light control with alternating sheer and opaque fabric bands."},
{name:"Roller Blinds",category:"Indoor",filters:["indoor","fabric"],material:"Fabric",image:"https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=85",desc:"Clean, practical window covering available in a wide range of fabrics, colours and openness levels."},
{name:"Vertical Blinds",category:"Indoor",filters:["indoor","fabric"],material:"Fabric",image:"https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=900&q=85",desc:"A practical solution for large windows and sliding doors with adjustable light control."},
{name:"Aluminium Venetian",category:"Indoor",filters:["indoor","aluminium"],material:"Aluminium",image:"https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=900&q=85",desc:"Durable horizontal slats with precise privacy and light adjustment."},
{name:"Timber / Meranti Venetian",category:"Indoor",filters:["indoor","wood"],material:"Meranti / Timber",image:"https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=900&q=85",desc:"Warm natural timber character for residential and premium interior spaces."},
{name:"Roman Blinds",category:"Indoor",filters:["indoor","fabric"],material:"Fabric",image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85",desc:"Soft, elegant folds that add a refined finish to living and bedroom spaces."},
{name:"PVC Outdoor Blinds",category:"Outdoor",filters:["outdoor","pvc"],material:"PVC",image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85",desc:"Outdoor screening designed to help protect areas from sun, wind and weather."},
{name:"Bamboo Outdoor Blinds",category:"Outdoor",filters:["outdoor","bamboo"],material:"Bamboo",image:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85",desc:"Natural bamboo texture for patios, verandas and outdoor entertaining spaces."},
{name:"Wooden Outdoor Blinds",category:"Outdoor",filters:["outdoor","wood"],material:"Meranti / Wood",image:"https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=85",desc:"Wood-based outdoor shading with a natural architectural appearance."},
{name:"ZipTrak Blinds",category:"Outdoor",filters:["outdoor","pvc"],material:"PVC / Fabric",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",desc:"Track-guided outdoor blinds for flexible weather and glare control."},
{name:"Motorized Blinds",category:"Motorized",filters:["motorized","indoor","outdoor","fabric"],material:"Multiple options",image:"https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=900&q=85",desc:"Convenient automated control for selected indoor and outdoor blind systems."},
{name:"Honeycomb Blinds",category:"Indoor",filters:["indoor","fabric"],material:"Fabric",image:"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85",desc:"Cellular construction designed to provide a soft appearance and added insulation."}];
const grid=document.getElementById("productGrid"),modal=document.getElementById("productModal");
function render(filter="all"){const list=filter==="all"?products:products.filter(p=>p.filters.includes(filter));grid.innerHTML=list.map(p=>`<article class="product-card" data-index="${products.indexOf(p)}"><img src="${p.image}" alt="${p.name}"><div class="p-body"><span class="tag">${p.category} · ${p.material}</span><h3>${p.name}</h3><p>${p.desc}</p></div></article>`).join("");document.querySelectorAll(".product-card").forEach(c=>c.onclick=()=>openProduct(+c.dataset.index))}
function openProduct(i){let p=products[i];document.getElementById("modalImage").src=p.image;document.getElementById("modalTitle").textContent=p.name;document.getElementById("modalCategory").textContent=p.category+" BLINDS";document.getElementById("modalDescription").textContent=p.desc;document.getElementById("modalMaterial").textContent=p.material;modal.classList.add("open")}
function closeModal(){modal.classList.remove("open")}
document.querySelector(".modal-close").onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.onkeydown=e=>{if(e.key==="Escape")closeModal()};
document.querySelectorAll("[data-product-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.productFilter)});
document.querySelectorAll(".category-card").forEach(b=>b.onclick=()=>{let f=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x.dataset.productFilter===f));render(f);document.getElementById("all-products").scrollIntoView({behavior:"smooth"})});
const toggle=document.querySelector(".menu-toggle"),nav=document.getElementById("mainNav");toggle.onclick=()=>nav.classList.toggle("open");document.querySelectorAll(".nav a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
document.getElementById("quoteForm").onsubmit=e=>{e.preventDefault();document.getElementById("formNote").textContent="Thank you. Demo form submitted. Connect this form to email/CRM/WhatsApp before launch."};render();
